# Generated by Django 4.2.7 on 2023-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="logo",
            field=models.ImageField(
                default="default/authentication/default.jpg",
                upload_to="authentication/%Y/%m/%d/",
            ),
        ),
    ]
